## Configuracion de Spring
spring:
  application:
    name: facets-search-engine

## Configuracion de Instancia 
server:
  port: 8088
  fullAddress: https://facets-search-engine-production.up.railway.app
## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: facets-search-engine

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:master-unir-8881725203.us-west-2.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:q4c0wee2ed}
    password: ${ELASTICSEARCH_PWD:1jmk8acg34}
logging:
  level:
    tracer: TRACE