## Configuracion de Spring
spring:
  application:
    name: facets-search-engine

## Configuracion de Instancia 
server:
  port: 8088

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:master-unir-8881725203.us-west-2.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:q4c0wee2ed}
    password: ${ELASTICSEARCH_PWD:1jmk8acg34}
logging:
  level:
    tracer: TRACE